[workspace]
members = [
    "basic",
]
resolver = "2"

[workspace.dependencies]
nu-cli = "0.103"
nu-command = "0.103"
nu-protocol = "0.103"
nu-cmd-lang = "0.103"
nu-engine = "0.103"
nu-parser = "0.103"