[package]
name = "mini-nu"
version = "0.1.0"
edition = "2021"

[dependencies]
nu-cli = "0.103"
nu-command = "0.103"
nu-protocol = "0.103"
nu-cmd-lang = "0.103"
nu-engine = "0.103"
nu-parser = "0.103"
